name: "Continuous Integration"
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.0

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false
    steps:
    - name: Build
      uses: actions/drf-react-template-framework-build@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Test with pytest
      run: |
        poetry run pytest --cov
