name: "Continuous Integration"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: |
        pipenv install --dev
    - name: Run pre-commit
      uses: pre-commit/action@v2.0.0
    - name: Test with pytest
      run: |
        pipenv run pytest